name = "CompositionalCounts"
uuid = "d0e53907-0033-4a7a-a8ae-f68b5fb6389e"
authors = ["Jonathan D.A. Jewell <6759885+hyperpolymath@users.noreply.github.com>"]
version = "0.1.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[weakdeps]
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"

[extensions]
CompositionalCountsRCallExt = "RCall"

[compat]
LinearAlgebra = "1"
RCall = "0.14"
SpecialFunctions = "2"
julia = "1.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
